using RT.Lingo;

namespace AccountsWeb
{
    [LingoStringClass]
    sealed partial class TrayFormTranslation
    {
        [LingoAutoGenerated]
        public TrString TrayForm = "TrayForm";
    }

    [LingoStringClass]
    sealed partial class TrayMenuTranslation
    {
        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.TrayMenu)]
        public TrString miOpenInBrowser = "Open in &browser";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.TrayMenu)]
        public TrString miReload = "&Reload";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.TrayMenu)]
        public TrString miSettings = "&Settings...";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.TrayMenu)]
        public TrString miNewFile = "&New file...";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.TrayMenu)]
        public TrString miOpenFile = "&Open file...";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.TrayMenu)]
        public TrString miOpenRecent = "Open r&ecent";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.TrayMenu)]
        public TrString miAbout = "&About... (in browser)";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.TrayMenu)]
        public TrString miExit = "E&xit";
    }

    [LingoStringClass]
    sealed partial class ConfigFormTranslation
    {
        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString ConfigForm = "AccountsWeb Configuration";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString tabPaths = "General";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString btnLanguage = "Select &Language";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString lblBaseCurrency = "&Base currency:";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString btnBrowseGnuCash = "...";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString lblGnuCashFile = "&GnuCash file location:";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString tabGeneral = "Network";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString lblListenPort = "Listen on &port:";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString btnOK = "OK";

        [LingoAutoGenerated]
        [LingoInGroup(TrGroup.SettingsDialog)]
        public TrString btnCancel = "Cancel";
    }
}
